# Generated by Django 5.2 on 2025-04-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('teams', models.CharField(max_length=255)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('game', models.CharField(max_length=50)),
            ],
        ),
    ]
