# Generated by Django 5.2 on 2025-05-05 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_teammanager_user_alter_fixture_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('team_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='badmintonmanager',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.game'),
        ),
        migrations.AddField(
            model_name='cricketmanager',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.game'),
        ),
        migrations.AddField(
            model_name='footballmanager',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.game'),
        ),
    ]
