# Generated by Django 5.2.1 on 2025-05-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_game_badmintonmanager_game_cricketmanager_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badmintonmanager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manager_images/'),
        ),
        migrations.AddField(
            model_name='badmintonplayer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/'),
        ),
        migrations.AddField(
            model_name='cricketmanager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manager_images/'),
        ),
        migrations.AddField(
            model_name='cricketplayer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/'),
        ),
        migrations.AddField(
            model_name='footballmanager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manager_images/'),
        ),
        migrations.AddField(
            model_name='footballplayer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/'),
        ),
    ]
